// Copyright 2025 The FlutterJS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import esbuild from 'esbuild';
import { readFileSync, writeFileSync, readdirSync, statSync, watch, existsSync, copyFileSync, mkdirSync } from 'fs';
import { join, relative, extname, dirname } from 'path';
import { fileURLToPath } from 'url';
import { execSync } from 'child_process';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const srcDir = 'src';
const outDir = 'dist';

/**
 * ✅ Recursively find ALL .js files in src/
 */
function getAllJsFiles(dir) {
  const files = [];
  const items = readdirSync(dir);

  for (const item of items) {
    const fullPath = join(dir, item);
    const stat = statSync(fullPath);

    if (stat.isDirectory()) {
      files.push(...getAllJsFiles(fullPath));
    } else if (extname(item) === '.js') {
      files.push(fullPath);
    }
  }

  return files;
}

/**
 * Compile Dart files from lib/ to src/
 */
async function compileDartToJS() {
  const packageRoot = join(__dirname, '..');
  const libDir = join(packageRoot, 'lib');

  if (!existsSync(libDir)) {
    console.log('⚠️  No lib/ directory found, skipping Dart compilation\n');
    return;
  }

  console.log('📚 Compiling Dart files from lib/...\n');

  try {
    execSync(
      `dart run ../../../tool/build_package.dart ${packageRoot}`,
      { stdio: 'inherit', cwd: __dirname }
    );
    console.log('✅ Dart compilation complete\n');
  } catch (error) {
    console.error('❌ Dart compilation failed:', error.message);
    process.exit(1);
  }
}

/**
 * Build each .js file separately
 */
async function buildAllFiles() {
  try {
    console.log('🚀 Building @flutterjs/foundation...\n');

    // ✅ STAGE 1: Compile lib/ → src/ (if lib/ exists)
    await compileDartToJS();

    // ✅ STAGE 2: Find all .js files in src/
    const allFiles = getAllJsFiles(srcDir);

    console.log(`📁 Found ${allFiles.length} JS files in src/\n`);

    // Ensure dist/ directory exists
    if (!existsSync(outDir)) {
      mkdirSync(outDir, { recursive: true });
    }

    // ✅ Build each file separately, but COPY index.js directly
    // (esbuild with bundle:false strips `export *` barrel exports)
    for (const srcFile of allFiles) {
      const relativePath = relative(srcDir, srcFile);
      const outFile = join(outDir, relativePath);

      console.log(`📦 ${relativePath}`);

      // Barrel export files (index.js) must be copied directly.
      // esbuild with bundle:false turns `export * from './xxx.js'`
      // into an empty file (strips re-exports). So we fs.copy instead.
      if (relativePath === 'index.js' || relativePath.endsWith('\\index.js') || relativePath.endsWith('/index.js')) {
        copyFileSync(srcFile, outFile);
        console.log(`   ✓ Copied barrel export: ${relativePath}`);
        continue;
      }

      await esbuild.build({
        entryPoints: [srcFile],
        outfile: outFile,
        bundle: false,
        minify: false, // Disabled for debugging
        platform: 'browser',
        target: ['es2020'],
        format: 'esm',
        sourcemap: true,
      });
    }

    console.log();

    // ✅ STAGE 3: Generate exports based on all built files
    generateExports(allFiles);

    // Note: exports.json is already generated by Dart compiler
    // generateExportManifest() is now redundant

    console.log('✅ Build successful!\n');

  } catch (error) {
    console.error('❌ Build failed:', error);
    process.exit(1);
  }
}


/**
 * Auto-generate package.json exports in the exact format requested
 * "./core/widget_element.js" → "./dist/core/widget_element.js"
 */
function generateExports(sourceFiles) {
  const packageJsonPath = './package.json';
  const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf8'));

  const exports = {};

  // Main entry point
  exports['.'] = './dist/index.js';

  // ✅ Create export for EVERY built file with exact format
  for (const srcFile of sourceFiles) {
    const relativePath = relative(srcDir, srcFile);

    // Skip index.js - it's already the main entry
    if (relativePath === 'index.js') {
      continue;
    }

    // Convert path with .js extension:
    // core.js → ./core.js
    // core/widget_element.js → ./core/widget_element.js
    // material.js → ./material.js
    // widgets/compoment/multi_child_view.js → ./widgets/compoment/multi_child_view.js

    // Normalize slashes for Windows
    const normalizedPath = relativePath.replace(/\\/g, '/');
    const exportKey = './' + normalizedPath.replaceAll(".js", "");
    const exportPath = './dist/' + normalizedPath;

    exports[exportKey] = exportPath;
  }

  // Update package.json
  packageJson.exports = exports;
  packageJson.main = './dist/index.js';

  writeFileSync(packageJsonPath, JSON.stringify(packageJson, null, 2) + '\n');

  console.log('📝 Generated exports:\n');
  Object.entries(exports).forEach(([key, value]) => {
    console.log(`   "${key}": "${value}"`);
  });
  console.log();
}

// Note: generateExportManifest() removed - exports.json is now generated
// by the Dart compiler during the compileDartToJS() stage

/**
 * Watch mode - rebuild on file changes
 */
function watchMode() {
  console.log('👀 Watching for changes...\n');

  watch(srcDir, { recursive: true }, (eventType, filename) => {
    if (extname(filename) === '.js') {
      console.log(`\n⚡ ${filename} changed\n`);
      buildAllFiles();
    }
  });
}

// ✅ Check for --watch flag
const isWatchMode = process.argv.includes('--watch');

if (isWatchMode) {
  buildAllFiles().then(() => watchMode());
} else {
  buildAllFiles();
}