include: package:lints/recommended.yaml

analyzer:
  exclude:
    - "**/builder/**"
    - "**/.dart_tool/**"
    - "**/build/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/test/**"                    # Exclude all test directories
    - "**/node_modules/**"            # Exclude node_modules
    - "packages/**/dist/**"           # Exclude flutterjs_material dist
    - "examples/**/build/**"          # Exclude example build folders
    - "**/*.js"                        # Exclude all JavaScript files
    - "**/*.fjs"                       # Exclude ES modules
  
  # Performance optimizations
  language:
    strict-casts: false
    strict-inference: false
    strict-raw-types: false
  
  # Reduce analysis scope
  errors:
    # Downgrade some checks to improve speed
    todo: ignore
    deprecated_member_use: ignore
  
  # Enable strong mode for better performance
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true

linter:
  rules:
    # Disable heavy lint rules if needed
    # - avoid_print: false