include: package:lints/recommended.yaml

analyzer:
  exclude:
    - "**/builder/**"
    - "**/.dart_tool/**"
    - "**/build/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/test/**"
    - "**/node_modules/**"
    - "packages/**/dist/**"
    - "examples/**/build/**"
    - "**/*.js"
    - "**/*.fjs"
  
  # Performance optimizations
  language:
    strict-casts: false
    strict-inference: false
    strict-raw-types: false
  
  # Reduce analysis scope
  errors:
    todo: ignore
    deprecated_member_use: ignore
    use_super_parameters: ignore
    prefer_final_fields: ignore
    avoid_print: ignore
    unnecessary_brace_in_string_interps: ignore
    use_key_in_widget_constructors: ignore
    file_names: ignore
    non_constant_identifier_names: ignore
    unintended_html_in_doc_comment: ignore
    unused_element: ignore
    unnecessary_import: ignore
    implementation_imports: ignore
    unnecessary_library_name: ignore
    dangling_library_doc_comments: ignore
    must_be_immutable: ignore
    unused_catch_stack: ignore
    dead_code: ignore
    dead_null_aware_expression: ignore
    unrelated_type_equality_checks: ignore
    collection_methods_unrelated_type: ignore
    depend_on_referenced_packages: ignore
    annotate_overrides: ignore
  
  # Enable strong mode for better performance
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true

linter:
  rules:
    - avoid_print: false