# melos.yaml
name: flutterjs
packages:
  - packages/**
  - examples/**

scripts:
  bootstrap:
    run: melos bootstrap
    description: Bootstrap all Dart packages.

  init:
    run: dart run tool/init.dart
    description: Initialize all dependencies for Dart and JavaScript packages.

  test:all:
    run: melos exec --dir-exists="test" -- dart test
    description: Run tests for all Dart packages.
  
  analyze:all:
    run: melos exec -- dart analyze
    description: Analyze all Dart packages.